---
version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex  
    network_mode: host 
    environment:
    - PUID=1000 
    - PGID=1000
    - TZ=Europe/Madrid 
    - VERSION=docker
    volumes:
      - /mnt/docker:/config 
      - /mnt:/media 
    restart: unless-stopped